name: Publish Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs pull

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the release
      run: ./mvnw -B package

    - name: Publish the release
      run: |
        export  MAVEN_OPTS="-Xmx3g -XX:MaxMetaspaceSize=512m"
        ./mvnw -B jreleaser:release
