# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
      - name: Prepare the release
        run: ./mvnw -B release:prepare -DpushChanges=false
        env:
         GITHUB_TOKEN: ${{ github.token }}

      - name: Perform the release
        run: ./mvnw -B release:perform -DlocalCheckout=true -Darguments="-DskipTests -Dmaven.javadoc.skip=true assembly:assembly"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Bump pom version
        run : git push

      - name: Push tags
        run: git push --tags      
