# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Artifact Release and Tag

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
      - name: Remove SNAPSHOT version
        run: ./mvnw -B versions:set -DremoveSnapshot
        # env:
        # GITHUB_TOKEN: ${{ github.token }}

      - name: Build the release
        run: ./mvnw -B package

      - name: Commit and tag changes
        run : |
          release_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git add pom.xml 
          git commit -m 'Release $release_version'
          git tag $release_version

      - name: Move to next snapshot version
        run: |
          ./mvnw -B versions:set -DnextSnapshot
          git add pom.xml
          git commit -m 'Release $release_version'

      - name: Push tag and next version to branch
        run: |
          git push --tags
          git push --all
